### ISSUE TITLE
Adding support for Subaru SSM Protocol

### ISSUE THREAD

**Issue by borland667** [Joelzeller/CoPilot#2]
Hi there, I was looking to do something exactly like this but instead of using OBDII, use the Subaru specific protocol. I have an old Subaru Impreza that doesn't have OBD...

How do you think would be the best way to approach this? Given you know your code much better...

**Comment by Joelzeller** [comment]
Hi Osvaldo,

Unfortunately I do not know how to go about utilizing the Subaru protocol. I guess the first step would be to find how to connect with a dongle connected to the car's diagnostic port.  Could you find any devices that would plug into the car and either use wifi, bluetooth, or usb to connect to the pi?  If you find something like this, I would be happy to look more into it. But as I do not have your model year subaru, I will more than likely not be able to test as effectively as OBDII.  I wish you the best of luck as I do love an old Impreza!   What year is it btw?

**Comment by borland667** [comment]
Hey Joel, apologies if you thought I was asking you to do it! LOL. You've done pretty much everything I wanted to do, except for the specific subaru stuff :) which I will be happy to add.. just haven't done much with kivy so I'm a bit of a newbie there...

I do have a bit of testing code (meaning crappy but working code) which uses a serial ttl line with an usb converter. I had some done in arduino already but I wanted to do something better with a 7 inches touchscreen.

Now, what I wanted to do was a single dashboard showing all parameters at once. Similar to what you've done with the OBDII screens, but all in one screen. I was thinking it could be done generic enough to later down the track abstract the protocol used to gather the actual data.

Also have a couple of extra analog sensors for oil temp, pressure, o2 wideband and an accelerometer which I want to show in the same screen (Attaching a diagram of what I want the screen to look like)
![whatsapp image 2018-01-05 at 17 19 41](https://user-images.githubusercontent.com/4934582/34626727-b37bce44-f23c-11e7-883b-95da84a16b33.jpeg)

Any hints where to start would be greatly appreciated!

**Comment by borland667** [comment]
Sorry, forgot!!! I have an old classic impreza WRX STI 1997 JDM (blue) hehe :)
